# Generated by Django 5.2 on 2025-04-02 19:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Code')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Check-in Effettuato')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'verbose_name': 'Registrazione Evento',
                'verbose_name_plural': 'Registrazioni Eventi',
                'ordering': ['-created_at'],
            },
        ),
    ]
