# Generated by Django 5.2 on 2025-04-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Evento')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('date', models.DateTimeField(verbose_name='Data e Ora')),
                ('location', models.CharField(max_length=200, verbose_name='Luogo')),
                ('address', models.TextField(verbose_name='Indirizzo')),
                ('city', models.CharField(max_length=100, verbose_name='Città')),
                ('country', models.CharField(max_length=100, verbose_name='Paese')),
                ('cover_image', models.ImageField(upload_to='events/covers/', verbose_name='Immagine Copertina')),
                ('promo_video', models.URLField(blank=True, verbose_name='Video Promo')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('published', 'Pubblicato'), ('cancelled', 'Cancellato'), ('completed', 'Completato')], default='draft', max_length=20, verbose_name='Stato')),
                ('is_public', models.BooleanField(default=True, verbose_name='Pubblico')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='Max Partecipanti')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo Biglietto')),
                ('map_url', models.URLField(blank=True, verbose_name='URL Mappa')),
                ('contact_info', models.TextField(blank=True, verbose_name='Info Contatto')),
                ('table_booking_info', models.TextField(blank=True, verbose_name='Info Prenotazione Tavoli')),
                ('views_count', models.IntegerField(default=0, verbose_name='Visualizzazioni')),
                ('registered_count', models.IntegerField(default=0, verbose_name='Registrati')),
                ('checked_in_count', models.IntegerField(default=0, verbose_name='Check-in')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'ordering': ['-date'],
            },
        ),
    ]
