# Generated by Django 5.2 on 2025-04-02 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(limit_choices_to={'role__in': ['artist', 'verified_artist']}, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='events', to='media.media'),
        ),
        migrations.AddField(
            model_name='event',
            name='promoters',
            field=models.ManyToManyField(limit_choices_to={'role': 'promoter'}, related_name='promoted_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
