# Generated by Django 5.2 on 2025-04-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('image', models.ImageField(upload_to='artworks/', verbose_name='Immagine')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('is_digital', models.BooleanField(default=False, verbose_name='È digitale')),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='Hash Blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_for_auction', models.BooleanField(default=False, verbose_name='In asta')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Venduto')),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizzazioni')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Mi piace')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificato')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensioni')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Data Creazione Opera')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Luogo')),
            ],
            options={
                'verbose_name': 'Opera',
                'verbose_name_plural': 'Opere',
                'ordering': ['-created_at'],
            },
        ),
    ]
