# Generated by Django 5.2 on 2025-04-02 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Iniziale')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Attuale')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ora Inizio')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ora Fine')),
                ('last_bid_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('is_live', models.BooleanField(default=False, verbose_name='In Diretta')),
                ('min_bid_increment', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Incremento Minimo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='artworks.artwork')),
            ],
            options={
                'verbose_name': 'Asta',
                'verbose_name_plural': 'Aste',
                'ordering': ['-created_at'],
            },
        ),
    ]
