# Generated by Django 5.2 on 2025-04-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('status', models.CharField(choices=[('scheduled', 'Programmata'), ('live', 'In Diretta'), ('ended', 'Conclusa'), ('cancelled', 'Cancellata')], default='scheduled', max_length=20, verbose_name='Stato')),
                ('scheduled_start', models.DateTimeField(verbose_name='Inizio Programmato')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inizio Effettivo')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fine')),
                ('stream_url', models.URLField(blank=True, verbose_name='URL Stream')),
                ('stream_key', models.CharField(blank=True, max_length=100, verbose_name='Chiave Stream')),
                ('video_url', models.URLField(blank=True, verbose_name='URL Replay')),
                ('viewers_count', models.IntegerField(default=0, verbose_name='Numero Spettatori')),
                ('peak_viewers', models.IntegerField(default=0, verbose_name='Picco Spettatori')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durata')),
                ('is_public', models.BooleanField(default=True, verbose_name='Pubblica')),
                ('allow_chat', models.BooleanField(default=True, verbose_name='Chat Attiva')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Commenti Attivi')),
            ],
            options={
                'verbose_name': 'Live Stream',
                'verbose_name_plural': 'Live Streams',
                'ordering': ['-scheduled_start'],
            },
        ),
    ]
