# Generated by Django 5.2 on 2025-04-02 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('file', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'webm', 'mp3', 'wav', 'pdf', 'doc', 'docx'])], verbose_name='File')),
                ('type', models.CharField(choices=[('image', 'Immagine'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Documento')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('processing', 'In Elaborazione'), ('ready', 'Pronto'), ('error', 'Errore')], default='processing', max_length=20, verbose_name='Stato')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Caricato il')),
                ('file_size', models.IntegerField(help_text='Dimensione in bytes', verbose_name='Dimensione File')),
                ('duration', models.DurationField(blank=True, help_text='Per video/audio', null=True, verbose_name='Durata')),
                ('width', models.IntegerField(blank=True, help_text='Per immagini/video', null=True, verbose_name='Larghezza')),
                ('height', models.IntegerField(blank=True, help_text='Per immagini/video', null=True, verbose_name='Altezza')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/', verbose_name='Thumbnail')),
                ('preview_url', models.URLField(blank=True, verbose_name='URL Preview')),
                ('is_public', models.BooleanField(default=True, verbose_name='Pubblico')),
                ('access_token', models.CharField(blank=True, max_length=100, verbose_name='Token Accesso')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
