# Generated by Django 5.2 on 2025-04-07 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('artwork', 'Opera'), ('event', 'Evento'), ('stream', 'Live Stream'), ('auction', 'Asta')], max_length=50, verbose_name='Tipo Contenuto')),
                ('content_id', models.IntegerField(verbose_name='ID Contenuto')),
                ('action', models.CharField(choices=[('view', 'Visualizzazione'), ('like', 'Mi piace'), ('bid', 'Offerta'), ('register', 'Registrazione'), ('check_in', 'Check-in'), ('comment', 'Commento'), ('share', 'Condivisione')], max_length=50, verbose_name='Azione')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadati')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='Indirizzo IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interazione Utente',
                'verbose_name_plural': 'Interazioni Utenti',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'content_type', 'content_id'], name='users_useri_user_id_4e4a4e_idx'), models.Index(fields=['timestamp'], name='users_useri_timesta_390cf1_idx')],
            },
        ),
    ]
